# Declares the azurerm remote backend. Values are supplied at init time:
#   - Locally: `terraform init -backend-config=backend.hcl`
#   - CI:      `terraform init -backend-config="key=value" ...` (see workflows)
# The values themselves live in backend.hcl (gitignored, generated by
# scripts/bootstrap-tf-state.sh) or in GitHub environment variables.
terraform {
  backend "azurerm" {}
}
