#!/usr/bin/env bash
# Create the Azure resources that hold Terraform remote state. Idempotent:
# safe to re-run if any step has already been performed.

set -euo pipefail

usage() {
  cat <<USAGE
Usage: $0 \\
  --subscription-id <id> \\
  --location <azure-region> \\
  --resource-group <name> \\
  --storage-account <name> \\
  [--container <name>] \\
  [--state-key <name>] \\
  [--set-vars] \\
  [--repo <owner>/<repo>] \\
  [--environment <name>]

Defaults:
  --container     tfstate
  --state-key     ai-chat/dev.tfstate
  --environment   dev

Use --set-vars to push TF_STATE_* and AZURE_LOCATION directly into the GitHub
environment via the gh CLI (instead of printing them for manual copy-paste).
Requires gh authenticated (run \`gh auth login\` once; the default scopes are
sufficient). When --repo is omitted, gh infers it from the current git remote.
USAGE
}

SUBSCRIPTION_ID=""
LOCATION=""
RESOURCE_GROUP=""
STORAGE_ACCOUNT=""
CONTAINER="tfstate"
STATE_KEY="ai-chat/dev.tfstate"
SET_VARS="false"
REPO=""
ENVIRONMENT="dev"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --subscription-id) SUBSCRIPTION_ID="$2"; shift 2 ;;
    --location) LOCATION="$2"; shift 2 ;;
    --resource-group) RESOURCE_GROUP="$2"; shift 2 ;;
    --storage-account) STORAGE_ACCOUNT="$2"; shift 2 ;;
    --container) CONTAINER="$2"; shift 2 ;;
    --state-key) STATE_KEY="$2"; shift 2 ;;
    --set-vars) SET_VARS="true"; shift ;;
    --repo) REPO="$2"; shift 2 ;;
    --environment) ENVIRONMENT="$2"; shift 2 ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown flag: $1" >&2; usage; exit 1 ;;
  esac
done

if [[ -z "$SUBSCRIPTION_ID" || -z "$LOCATION" || -z "$RESOURCE_GROUP" || -z "$STORAGE_ACCOUNT" ]]; then
  usage
  exit 1
fi

echo "==> Setting subscription $SUBSCRIPTION_ID"
az account set --subscription "$SUBSCRIPTION_ID"

echo "==> Ensuring resource group $RESOURCE_GROUP exists in $LOCATION"
az group create --name "$RESOURCE_GROUP" --location "$LOCATION" --output none

echo "==> Ensuring storage account $STORAGE_ACCOUNT exists"
if az storage account show --name "$STORAGE_ACCOUNT" --resource-group "$RESOURCE_GROUP" --output none 2>/dev/null; then
  echo "    storage account already exists"
else
  az storage account create \
    --name "$STORAGE_ACCOUNT" \
    --resource-group "$RESOURCE_GROUP" \
    --location "$LOCATION" \
    --sku Standard_LRS \
    --kind StorageV2 \
    --allow-blob-public-access false \
    --output none
fi

echo "==> Ensuring blob container $CONTAINER exists"
az storage container create \
  --name "$CONTAINER" \
  --account-name "$STORAGE_ACCOUNT" \
  --auth-mode login \
  --output none

INFRA_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../infra" && pwd)"
BACKEND_HCL="$INFRA_DIR/backend.hcl"
echo "==> Writing $BACKEND_HCL for local Terraform usage"
cat >"$BACKEND_HCL" <<EOF
# Generated by scripts/bootstrap-tf-state.sh. Gitignored; safe to regenerate.
# Used locally: \`terraform -chdir=infra init -backend-config=backend.hcl\`.
# CI passes equivalent -backend-config flags from GitHub environment variables.
resource_group_name  = "$RESOURCE_GROUP"
storage_account_name = "$STORAGE_ACCOUNT"
container_name       = "$CONTAINER"
key                  = "$STATE_KEY"
EOF

print_values() {
  cat <<NEXT

Done. Set these as GitHub environment variables (Settings -> Environments -> $ENVIRONMENT):

  TF_STATE_RESOURCE_GROUP   = $RESOURCE_GROUP
  TF_STATE_STORAGE_ACCOUNT  = $STORAGE_ACCOUNT
  TF_STATE_CONTAINER        = $CONTAINER
  TF_STATE_KEY              = $STATE_KEY
  AZURE_LOCATION            = $LOCATION

Tip: re-run with --set-vars to push these straight into GitHub via the gh CLI
(needs \`gh auth login\` once).

Local Terraform is ready: infra/backend.hcl has been written with the values above.
Run \`terraform -chdir=infra init -backend-config=backend.hcl\` next.
NEXT
}

if [[ "$SET_VARS" != "true" ]]; then
  print_values
  exit 0
fi

if ! command -v gh >/dev/null 2>&1; then
  echo "==> --set-vars requested but gh CLI is not installed." >&2
  echo "    Install it from https://cli.github.com/ then re-run, or copy the values manually:" >&2
  print_values
  exit 1
fi

if ! gh auth status >/dev/null 2>&1; then
  echo "==> --set-vars requested but gh is not authenticated." >&2
  echo "    Run \`gh auth login\` (default scopes are sufficient) then re-run, or copy the values manually:" >&2
  print_values
  exit 1
fi

if [[ -z "$REPO" ]]; then
  REPO=$(gh repo view --json nameWithOwner -q .nameWithOwner 2>/dev/null || true)
  if [[ -z "$REPO" ]]; then
    echo "==> Could not infer --repo from the current git remote. Pass --repo <owner>/<repo>." >&2
    exit 1
  fi
fi

echo "==> Ensuring GitHub environment '$ENVIRONMENT' exists in $REPO"
gh api -X PUT "repos/$REPO/environments/$ENVIRONMENT" --silent

echo "==> Writing TF_STATE_* and AZURE_LOCATION to $REPO environment $ENVIRONMENT"
gh variable set TF_STATE_RESOURCE_GROUP  --repo "$REPO" --env "$ENVIRONMENT" --body "$RESOURCE_GROUP"
gh variable set TF_STATE_STORAGE_ACCOUNT --repo "$REPO" --env "$ENVIRONMENT" --body "$STORAGE_ACCOUNT"
gh variable set TF_STATE_CONTAINER       --repo "$REPO" --env "$ENVIRONMENT" --body "$CONTAINER"
gh variable set TF_STATE_KEY             --repo "$REPO" --env "$ENVIRONMENT" --body "$STATE_KEY"
gh variable set AZURE_LOCATION           --repo "$REPO" --env "$ENVIRONMENT" --body "$LOCATION"

cat <<NEXT

Done. Variables set on $REPO / $ENVIRONMENT.
Two options from here:

1. Run github workflow to deploy infrastructure
2. Local Terraform is ready: infra/backend.hcl has been written.
   Run \`terraform -chdir=infra init -backend-config=backend.hcl\`.
  > Check infra/ folder for more details on how to deploy terraform.
  Quickstart:
  cd infra/
  terraform init
  terraform apply -var="use_bootstrap_images=true"
NEXT
